var mapsNormal		 = new Array( new Map(1, "mapPreviews/1.png", "Die Erste", 5, false),
	                              new Map(2, "mapPreviews/2.png", "Die Zweite", 5, false),
	                              new Map(3, "mapPreviews/3.png", "Die Dritte", 5, false),
	                              new Map(4, "mapPreviews/4.png", "", 5, false),
	                              new Map(5, "mapPreviews/5.png", "", 5, false),
	                              new Map(6, "mapPreviews/6.png", "", 5, false),
	                              new Map(7, "mapPreviews/7.png", "Sachsenring", 5, false),
	                              new Map(8, "mapPreviews/8.png", "Eurospeedway", 5, false),
	                              new Map(9, "mapPreviews/9.png", "Dragster-Race", 5, false),
	                              new Map(10, "mapPreviews/10.png", "", 5, false),
	                              new Map(11, "mapPreviews/11.png", "Go for Gold", 4, false),
	                              new Map(12, "mapPreviews/12.png", "Yaba hatte viel Zeit", 8, false),
	                              new Map(13, "mapPreviews/13.png", "", 7, false),
	                              new Map(14, "mapPreviews/14.png", "", 5, false),
	                              new Map(15, "mapPreviews/15.png", "Hindernissrennen", 5, false),
	                              new Map(16, "mapPreviews/16.png", "Inkateppich", 8, false),
	                              new Map(17, "mapPreviews/17.png", "Nürburgring", 12, false),
	                              new Map(18, "mapPreviews/18.png", "Fruitmap", 4, false),
	                              new Map(19, "mapPreviews/19.png", "The Cube", 4, false),
	                              new Map(20, "mapPreviews/20.png", "Scorpion", 8, false),
	                              new Map(21, "mapPreviews/21.png", "Rennstrecke", 5, false),
	                              new Map(22, "mapPreviews/22.png", "Das Weeeeee", 6, false),
	                              new Map(23, "mapPreviews/23.png", "Bald ist Weihnachten", 48, false),
	                              new Map(24, "mapPreviews/24.png", "More Ways", 9, false),
	                              new Map(25, "mapPreviews/25.png", "-----", 0, false),
	                              new Map(26, "mapPreviews/26.png", "Schnecke", 6, false),
	                              new Map(27, "mapPreviews/27.png", "Holperstrecke", 7, false),
	                              new Map(28, "mapPreviews/28.png", "Kreuzzug", 9, false),
	                              new Map(29, "mapPreviews/29.png", "FHTW Berlin I", 4, false),
	                              new Map(30, "mapPreviews/30.png", "-----", 0, false),
	                              new Map(31, "mapPreviews/31.png", "-----", 0, false),
	                              new Map(32, "mapPreviews/32.png", "-----", 0, false),
	                              new Map(33, "mapPreviews/33.png", "Highway To Hell", 5, false),
	                              new Map(34, "mapPreviews/34.png", "Flugplatz", 20, false),
	                              new Map(35, "mapPreviews/35.png", "Speedway", 21, false),
	                              new Map(36, "mapPreviews/36.png", "Regenwaldpiste", 15, false),
	                              new Map(37, "mapPreviews/37.png", "Nadelöhr II", 10, false),
	                              new Map(38, "mapPreviews/38.png", "Gentlemen's Agreement", 8, false),
	                              new Map(39, "mapPreviews/39.png", "-----", 0, false),
	                              new Map(40, "mapPreviews/40.png", "CS-Kurve", 15, false),
	                              new Map(41, "mapPreviews/41.png", "Karofisch", 6, false),
	                              new Map(42, "mapPreviews/42.png", "Karokatze", 7, false),
	                              new Map(43, "mapPreviews/43.png", "Karo-F", 10, false),
	                              new Map(44, "mapPreviews/44.png", "Tux", 10, false),
	                              new Map(45, "mapPreviews/45.png", "Gruß aus Braunschweig", 12, false),
	                              new Map(46, "mapPreviews/46.png", "Noch ne Rundstrecke", 10, false),
	                              new Map(47, "mapPreviews/47.png", "-----", 0, false),
	                              new Map(48, "mapPreviews/48.png", "-----", 0, false),
	                              new Map(49, "mapPreviews/49.png", "Vermondy", 4, false),
	                              new Map(50, "mapPreviews/50.png", "Planet Apes", 7, false),
	                              new Map(51, "mapPreviews/51.png", "You've Got Mail", 4, false),
	                              new Map(52, "mapPreviews/52.png", "-----", 0, false),
	                              new Map(53, "mapPreviews/53.png", "Flussschleife", 12, false),
	                              new Map(54, "mapPreviews/54.png", "Klapperschlange II", 8, false),
	                              new Map(55, "mapPreviews/55.png", "Rush Hour", 27, false),
	                              new Map(56, "mapPreviews/56.png", "Interlagos", 6, false),
	                              new Map(57, "mapPreviews/57.png", "Dubya", 11, false),
	                              new Map(58, "mapPreviews/58.png", "Eisbären Berlin", 6, false),
	                              new Map(59, "mapPreviews/59.png", "-----", 0, false),
	                              new Map(60, "mapPreviews/60.png", "-----", 0, false),
	                              new Map(61, "mapPreviews/61.png", "Mushroom Cup - Mario Circuit 1", 8, false),
	                              new Map(62, "mapPreviews/62.png", "Mushroom Cup - Donut Plains 1", 8, false),
	                              new Map(63, "mapPreviews/63.png", "Mushroom Cup - Ghost Valley 1", 8, false),
	                              new Map(64, "mapPreviews/64.png", "Mushroom Cup - Bowser Castle 1", 8, false),
	                              new Map(65, "mapPreviews/65.png", "Mushroom Cup - Mario Circuit 2", 8, false),
	                              new Map(66, "mapPreviews/66.png", "Flower Cup - Choco Island 1", 8, false),
	                              new Map(67, "mapPreviews/67.png", "Flower Cup - Ghost Valley 2", 8, false),
	                              new Map(68, "mapPreviews/68.png", "Flower Cup - Donut Plains 2", 8, false),
	                              new Map(69, "mapPreviews/69.png", "Flower Cup - Bowser Castle 2", 8, false),
	                              new Map(70, "mapPreviews/70.png", "Flower Cup - Mario Circuit 3", 8, false),
	                              new Map(71, "mapPreviews/71.png", "Star Cup - Koopa Beach 1", 8, false),
	                              new Map(72, "mapPreviews/72.png", "Star Cup - Choco Island 2", 8, false),
	                              new Map(73, "mapPreviews/73.png", "Star Cup - Bowser Castle 3", 8, false),
	                              new Map(74, "mapPreviews/74.png", "Star Cup - Vanilla Lake 1", 8, false),
	                              new Map(75, "mapPreviews/75.png", "Star Cup - Mario Circuit 4", 8, false),
	                              new Map(76, "mapPreviews/76.png", "Special Cup - Donut Plains 3", 8, false),
	                              new Map(77, "mapPreviews/77.png", "Special Cup - Koopa Beach 2", 8, false),
	                              new Map(78, "mapPreviews/78.png", "Special Cup - Ghost Valley 3", 8, false),
	                              new Map(79, "mapPreviews/79.png", "Special Cup - Vanilla Lake 2", 8, false),
	                              new Map(80, "mapPreviews/80.png", "Special Cup - Rainbow Road", 8, false),
	                              new Map(81, "mapPreviews/81.png", "-----", 0, false),
	                              new Map(82, "mapPreviews/82.png", "Istanbuler Ehrenrunde", 8, false),
	                              new Map(83, "mapPreviews/83.png", "Checkpoint-Strecke", 13, false),
	                              new Map(84, "mapPreviews/84.png", "Race the Leaf", 4, false),
	                              new Map(85, "mapPreviews/85.png", "Race the other Leaf", 4, false),
	                              new Map(86, "mapPreviews/86.png", "Karopapier", 4, false),
	                              new Map(87, "mapPreviews/87.png", "Stern", 5, false),
	                              new Map(88, "mapPreviews/88.png", "Nicki Lauda", 9, false),
	                              new Map(89, "mapPreviews/89.png", "Kaffeepause", 9, false),
	                              new Map(90, "mapPreviews/90.png", "Einfach den Pfeilen folgen", 8, false),
	                              new Map(91, "mapPreviews/91.png", "Deutschlandtour", 6, false),
	                              new Map(92, "mapPreviews/92.png", "Schnitzeljagd", 14, false),
	                              new Map(93, "mapPreviews/93.png", "Dove", 6, false),
	                              new Map(94, "mapPreviews/94.png", "Taschenrechner", 6, false),
	                              new Map(95, "mapPreviews/95.png", "Moebius", 16, false),
	                              new Map(96, "mapPreviews/96.png", "Wheel", 12, false),
	                              new Map(97, "mapPreviews/97.png", "KS Raceway", 10, false),
	                              new Map(98, "mapPreviews/98.png", "Hauskarte des ZoC-Clans", 6, false),
	                              new Map(99, "mapPreviews/99.png", "Honeynut Loops", 9, false),
	                              new Map(100, "mapPreviews/100.png", "-----", 0, false),
	                              new Map(101, "mapPreviews/101.png", "Flora Ring", 8, false),
	                              new Map(102, "mapPreviews/102.png", "Flowerpower", 9, false),
	                              new Map(103, "mapPreviews/103.png", "KaroHawaii", 7, false),
	                              new Map(104, "mapPreviews/104.png", "Chaosmap", 8, false),
	                              new Map(105, "mapPreviews/105.png", "XOSOFOX", 1, false),
	                              new Map(106, "mapPreviews/106.png", "-----", 0, false),
	                              new Map(107, "mapPreviews/107.png", "Binford", 10, false),
	                              new Map(108, "mapPreviews/108.png", "Für Annie :wavey:", 10, false),
	                              new Map(109, "mapPreviews/109.png", "Das Haus vom Nikolaus", 6, false),
	                              new Map(110, "mapPreviews/110.png", "Final Lap", 3, false),
	                              new Map(111, "mapPreviews/111.png", "Yin und Yang", 8, false),
	                              new Map(112, "mapPreviews/112.png", "Bass-Dezett", 10, false),
	                              new Map(113, "mapPreviews/113.png", "-----", 0, false),
	                              new Map(114, "mapPreviews/114.png", "Fischi", 6, false),
	                              new Map(115, "mapPreviews/115.png", "-----", 0, false),
	                              new Map(116, "mapPreviews/116.png", "Silbermond", 8, false),
	                              new Map(117, "mapPreviews/117.png", "Lets rock", 10, false),
	                              new Map(118, "mapPreviews/118.png", "lol", 8, false),
	                              new Map(119, "mapPreviews/119.png", "Monaco", 5, false),
	                              new Map(120, "mapPreviews/120.png", "1vs1vs1vs1", 4, false),
	                              new Map(121, "mapPreviews/121.png", "Knubbelbubbeldings", 4, false),
	                              new Map(122, "mapPreviews/122.png", "Bahrain", 5, false),
	                              new Map(123, "mapPreviews/123.png", "Miez", 6, false),
	                              new Map(124, "mapPreviews/124.png", "Bunt", 12, false),
	                              new Map(125, "mapPreviews/125.png", "Luis Royo", 12, false),
	                              new Map(126, "mapPreviews/126.png", "Audi", 10, false),
	                              new Map(127, "mapPreviews/127.png", "Ball", 28, false),
	                              new Map(128, "mapPreviews/128.png", "Chaos", 8, false),
	                              new Map(129, "mapPreviews/129.png", "KingT", 6, false),
	                              new Map(130, "mapPreviews/130.png", "Europa", 9, false),
	                              new Map(131, "mapPreviews/131.png", "Vatikan für Thargor", 6, false),
	                              new Map(132, "mapPreviews/132.png", "Kuh", 16, false),
	                              new Map(133, "mapPreviews/133.png", "Coke", 13, false),
	                              new Map(134, "mapPreviews/134.png", ":ZZZsleep:", 6, false),
	                              new Map(135, "mapPreviews/135.png", "Schnuller", 8, false),
                                new Map(136, "mapPreviews/136.png", "KaroKaffee", 5, false),
                                new Map(137, "mapPreviews/137.png", "Schneeman", 5, false)
                                );